/**
 * Renders the `.env` the stack reads.
 *
 * The comments in the output are the point: this file is read months later,
 * on a box, by someone deciding whether a value is safe to change. Every
 * secret says what breaks if it moves.
 */

export function renderEnvFile({
  hostname,
  bindAddress = "127.0.0.1",
  secrets,
  generatedAt = new Date(),
}) {
  return `# ─────────────────────────────────────────────────────────────────────────
# CIO Executive Dashboard — generated ${generatedAt.toISOString()}
# Generated by ops/generate-secrets.mjs. NEVER commit this file.
# The repository is public; these values live only on this box.
# ─────────────────────────────────────────────────────────────────────────

# ── Network ──────────────────────────────────────────────────────────────
# The tailnet hostname Caddy serves, and the host OAuth redirects come back
# to. Changing it means rebuilding the app image: it is compiled into the
# browser bundle.
TAILNET_HOSTNAME=${hostname}

# The address Caddy publishes on. Set this to this box's Tailscale IP
# (100.x.y.z from \`tailscale ip -4\`). 127.0.0.1 means the stack is reachable
# only from the box itself. Never set it to 0.0.0.0 — that would publish the
# dashboard on every interface, including whatever network you are on.
BIND_ADDRESS=${bindAddress}

# ── Supabase ─────────────────────────────────────────────────────────────
POSTGRES_DB=postgres

# Used by every service role. Changing it needs ops/db/init/02-roles.sql
# re-applied by hand — the init scripts only run on an empty data directory.
POSTGRES_PASSWORD=${secrets.postgresPassword}

# Signs and verifies every access token. Changing it invalidates the two API
# keys below, because they are JWTs signed with it, and signs everyone out.
JWT_SECRET=${secrets.jwtSecret}
JWT_EXPIRY=3600

# Safe in the browser — it grants nothing on its own, because Row Level
# Security decides what any request may see.
ANON_KEY=${secrets.anonKey}

# NOT safe in the browser. Bypasses RLS entirely. Server-side only, never
# prefixed NEXT_PUBLIC_, never logged.
SERVICE_ROLE_KEY=${secrets.serviceRoleKey}

REALTIME_ENC_KEY=${secrets.realtimeEncKey}
REALTIME_SECRET_KEY_BASE=${secrets.realtimeSecretKeyBase}

# Keep signup disabled. The single account is created once, by you, with the
# service-role call in docs/runbook-windows.md. Anyone who reaches the
# tailnet must not be able to enrol themselves.
DISABLE_SIGNUP=true
PASSWORD_MIN_LENGTH=12
MAILER_AUTOCONFIRM=true

# Optional SMTP, for password-recovery mail and (from P6) digests.
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_ADMIN_EMAIL=doug@theonefor.ai
SMTP_SENDER_NAME=CIO Dashboard

# ── Backups ──────────────────────────────────────────────────────────────
# Nightly at 02:00 by default.
BACKUP_CRON=0 2 * * *

# Second copy, on a different physical device — a second disk or the NAS.
# A folder on the same disk is not a second copy.
BACKUP_SECONDARY_PATH=./ops/backups-secondary

# Off-site copy. Both must be set for it to run; until then you have two of
# the three in 3-2-1, and every backup log says so.
# Public key from \`age-keygen\`. Keep the PRIVATE key off this box.
BACKUP_AGE_RECIPIENT=
# An rclone remote, e.g. offsite:cio-dashboard-backups
BACKUP_RCLONE_REMOTE=
RCLONE_CONFIG_PATH=./ops/backup/rclone

BACKUP_KEEP_DAILY=14
BACKUP_KEEP_WEEKLY=8
BACKUP_KEEP_MONTHLY=24

# ── Observability ────────────────────────────────────────────────────────
# Empty means errors are logged on this box and go nowhere else. Setting a
# DSN sends error reports off the box — read docs/threat-model.md first.
SENTRY_DSN=
DASHBOARD_ENVIRONMENT=production
`;
}
